---
# tasks file for wordpress
    - name:        Download Wordpress
      get_url:
       url:        http://wordpress.org/latest.tar.gz
       dest:       /tmp/wordpress.tar.gz
    - unarchive:
       src:        /tmp/wordpress.tar.gz
       dest:       /tmp
       remote_src: yes
    - copy:
        src:       "wp-config.php"
        dest:      /tmp/wordpress/
    - name:        sync word press
      command:     /usr/bin/rsync -avP /tmp/wordpress/ /usr/share/nginx/html/
    - name:        Create file for upload content
      file:
       path:       /usr/share/nginx/html/wp-content/uploads
       state:      directory
       mode:       0755
    - name:        Change ownership for "uploads"
      file:
        dest:      /usr/share/nginx/html/
        state:     directory
        owner:     nginx
        group:     nginx
        recurse:   yes
      notify:
        - restart mariadb
        - Restart nginx
        - Restart php-fpm
...